#!/usr/bin/env node
// scripts/vendor-ocr.mjs
//
// Copies the OCR engine's binary assets from node_modules into public/ocr/,
// so the browser fetches them same-origin instead of tesseract.js's default
// of a jsDelivr/unpkg CDN (which §1 forbids outright: "No file may leave the
// device. Zero network calls at runtime.").
//
// public/ocr/ is .gitignore'd (27 MB of binaries has no business in git —
// see .gitignore) and regenerated by this script, which runs automatically
// before `npm run build` / `npm run dev` (see the "prebuild"/"predev" scripts
// in package.json) and can be run directly as `npm run vendor:ocr`.
//
// What gets copied, and why these exact files:
//   * worker.min.js         — tesseract.js's own worker-script entry point.
//   * tesseract-core-simd-lstm.wasm(.js)  — LSTM-only engine, SIMD build.
//     Smaller than the full tesseract-core-simd.wasm (which also carries the
//     obsolete legacy engine) at near-identical accuracy for LSTM-only use.
//   * tesseract-core-lstm.wasm(.js)       — same engine, non-SIMD, as the
//     fallback for browsers without WASM SIMD support (src/tools/data/ocr.op.ts
//     picks between the two at runtime via a feature probe).
//   * <lang>.traineddata.gz, from the "4.0.0_best_int" variant — 3-9x smaller
//     than the plain "4.0.0" variant at near-identical accuracy (measured:
//     eng 2.82 MB vs 10.42 MB; fra 0.67 MB vs 5.99 MB). Never the plain
//     variant — see the plan for the measured comparison.
//
// This script only copies files; it never installs additional language
// packs. The set of languages vendored is exactly the set already installed
// as `@tesseract.js-data/*` dependencies (see package.json).

import { copyFile, mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const NODE_MODULES = path.join(ROOT, 'node_modules');
const OUT_DIR = path.join(ROOT, 'public', 'ocr');
const LANG_OUT_DIR = path.join(OUT_DIR, 'lang-data');

/** Every language pack this project vendors, and its human-readable name for
 *  the editor's checkbox list. Codes match `@tesseract.js-data/<code>`.
 *  MUST stay in sync with OCR_LANGUAGES in src/tools/data/ocr-languages.ts —
 *  duplicated rather than shared because this is a plain Node script (no TS,
 *  no bundler) and that module is TypeScript consumed by the app itself. */
const LANGUAGES = [
  { code: 'eng', name: 'English' },
  { code: 'fra', name: 'French' },
  { code: 'deu', name: 'German' },
  { code: 'spa', name: 'Spanish' },
  { code: 'ita', name: 'Italian' },
  { code: 'por', name: 'Portuguese' },
  { code: 'nld', name: 'Dutch' },
  { code: 'pol', name: 'Polish' },
  { code: 'tur', name: 'Turkish' },
  { code: 'rus', name: 'Russian' },
  { code: 'ara', name: 'Arabic' },
  { code: 'vie', name: 'Vietnamese' },
  { code: 'chi_sim', name: 'Chinese (Simplified)' },
  { code: 'jpn', name: 'Japanese' },
  { code: 'kor', name: 'Korean' },
];

function fmtKB(bytes) {
  return `${(bytes / 1024).toFixed(1)} KB`;
}

/** Copy a file only if the destination is missing or a different size —
 *  cheap idempotency so re-running this on every `dev`/`build` is fast. */
async function copyIfChanged(src, dest) {
  const srcStat = await stat(src);
  try {
    const destStat = await stat(dest);
    if (destStat.size === srcStat.size) return { copied: false, bytes: srcStat.size };
  } catch {
    // dest does not exist yet — fall through to copy.
  }
  await mkdir(path.dirname(dest), { recursive: true });
  await copyFile(src, dest);
  return { copied: true, bytes: srcStat.size };
}

async function main() {
  const rows = [];

  // --- worker script ---------------------------------------------------
  const workerSrc = path.join(NODE_MODULES, 'tesseract.js', 'dist', 'worker.min.js');
  const workerDest = path.join(OUT_DIR, 'worker.min.js');
  rows.push({ label: 'worker.min.js', ...(await copyIfChanged(workerSrc, workerDest)) });

  // --- core WASM builds (LSTM-only: SIMD + non-SIMD fallback) ----------
  const coreFiles = [
    'tesseract-core-simd-lstm.wasm',
    'tesseract-core-simd-lstm.wasm.js',
    'tesseract-core-lstm.wasm',
    'tesseract-core-lstm.wasm.js',
  ];
  for (const file of coreFiles) {
    const src = path.join(NODE_MODULES, 'tesseract.js-core', file);
    const dest = path.join(OUT_DIR, file);
    rows.push({ label: file, ...(await copyIfChanged(src, dest)) });
  }

  // --- language data (best_int variant only) ----------------------------
  const manifestLanguages = [];
  for (const { code, name } of LANGUAGES) {
    const src = path.join(NODE_MODULES, '@tesseract.js-data', code, '4.0.0_best_int', `${code}.traineddata.gz`);
    const dest = path.join(LANG_OUT_DIR, `${code}.traineddata.gz`);
    const result = await copyIfChanged(src, dest);
    rows.push({ label: `lang-data/${code}.traineddata.gz`, ...result });
    manifestLanguages.push({ code, name, bytes: result.bytes });
  }

  // --- manifest: real per-language download sizes for the editor UI ----
  // No timestamp on purpose: the manifest's only job is reporting real byte
  // sizes, and a timestamp would make it churn on every run for no reason.
  const bytesOf = (label) => rows.find((r) => r.label === label)?.bytes ?? 0;
  const manifest = {
    languages: manifestLanguages,
    core: {
      simd: { file: 'tesseract-core-simd-lstm.wasm', bytes: bytesOf('tesseract-core-simd-lstm.wasm') },
      fallback: { file: 'tesseract-core-lstm.wasm', bytes: bytesOf('tesseract-core-lstm.wasm') },
    },
    worker: { file: 'worker.min.js', bytes: bytesOf('worker.min.js') },
  };
  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(path.join(OUT_DIR, 'languages.json'), JSON.stringify(manifest, null, 2));

  // --- report ------------------------------------------------------------
  const widest = Math.max(...rows.map((r) => r.label.length), 'File'.length);
  const pad = (s, n) => s + ' '.repeat(Math.max(0, n - s.length));
  console.log(`${pad('File', widest)}  ${'Size'.padStart(10)}  Status`);
  console.log('-'.repeat(widest + 24));
  let total = 0;
  for (const row of rows) {
    total += row.bytes;
    console.log(`${pad(row.label, widest)}  ${fmtKB(row.bytes).padStart(10)}  ${row.copied ? 'copied' : 'up to date'}`);
  }
  console.log('-'.repeat(widest + 24));
  console.log(`Total vendored: ${fmtKB(total)} (${(total / 1024 / 1024).toFixed(2)} MB) across ${rows.length} files`);
  console.log(`Manifest written: ${path.relative(ROOT, path.join(OUT_DIR, 'languages.json'))}`);
}

main().catch((err) => {
  console.error('vendor-ocr: failed');
  console.error(err);
  process.exitCode = 1;
});
